version: '3.8'

services:
  api:
    build: .
    container_name: yfinance-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload
